import React, { createContext, useContext, useState } from 'react';
import { TRANSLATIONS } from '../data/mockData';

const LanguageContext = createContext();

const GLOSSARY = {
  ta: {
    "Pending Procurement Reorder Requests": "நிலுவையில் உள்ள கொள்முதல் கோரிக்கைகள்",
    "Awaiting Manager PO Issuance": "மேலாளரின் ஒப்புதலுக்காக காத்திருக்கிறது",
    "No pending purchase requests. All branch inventory healthy.": "கொள்முதல் கோரிக்கைகள் இல்லை. அனைத்து கிளைகளும் ஆரோக்கியமாக உள்ளன.",
    "Approve & Issue PO": "ஒப்புதல் & PO வெளியிடு",
    "Issued Purchase Orders (POs)": "வழங்கப்பட்ட கொள்முதல் ஆர்டர்கள் (POs)",
    "POs sent from SmartMart Pro procurement manager.": "கொள்முதல் மேலாளரிடமிருந்து அனுப்பப்பட்ட ஆர்டர்கள்.",
    "No active purchase orders found.": "செயலில் உள்ள கொள்முதல் ஆர்டர்கள் எதுவும் இல்லை.",
    "AWAITING WAREHOUSE VERIFICATION": "கிடங்கு சரிபார்ப்பிற்காக காத்திருக்கிறது",
    "ACCEPT PO": "ஆர்டரை ஏற்றுக்கொள்",
    "MARK SHIPPED": "அனுப்பப்பட்டதாக குறிக்கவும்",
    "MARK DELIVERED": "விநியோகிக்கப்பட்டதாக குறிக்கவும்",
    "Incoming Shipments Verification": "உள்வரும் ஏற்றுமதி சரிபார்ப்பு",
    "Count and verify delivered supplier shipments before updating store inventory.": "சரக்குகளை புதுப்பிக்கும் முன் விநியோகங்களை சரிபார்க்கவும்.",
    "No delivered supplier orders waiting in the warehouse queue.": "காத்துருக்கும் விநியோகங்கள் எதுவும் இல்லை.",
    "RECEIVED QTY": "பெறப்பட்ட அளவு",
    "DAMAGED QTY": "சேதமடைந்த அளவு",
    "VERIFY & UPDATE INVENTORY": "இருப்பை சரிபார்த்து புதுப்பிக்கவும்",
    "Secure Handover OTP": "பாதுகாப்பான விநியோக OTP",
    "Confirm & Mark Delivered": "விநியோகத்தை உறுதிப்படுத்து",
    "Online Customer Storefront": "ஆன்லைன் வாடிக்கையாளர் கடை",
    "Fresh organic produce, dairy, bakery, beverages & pantry items delivered straight to your home in 10 minutes.": "10 நிமிடங்களில் உங்கள் வீட்டிற்கு வழங்கப்படும் புதிய தயாரிப்புகள்.",
    "Shop Catalog": "தயாரிப்பு பட்டியல்",
    "My Basket": "எனது கூடை",
    "Live Delivery Tracking & Reviews": "நேரடி கண்காணிப்பு & மதிப்புரைகள்",
    "Shopping Basket": "வாங்கும் கூடை",
    "Review selected items before triggering online payment gateway.": "பணம் செலுத்தும் முன் பொருட்களை சரிபார்க்கவும்.",
    "Checkout Gateway": "செக்அவுட் நுழைவாயில்",
    "FILE 18% GST RETURN": "18% GST தாக்கல் செய்",
    "LOG NEW EXPENSE": "புதிய செலவை பதிவுசெய்",
    "Gross Revenue (YTD)": "மொத்த வருவாய் (ஆண்டு)",
    "Operating Expenses": "இயக்க செலவுகள்",
    "Net Operating Profit": "நிகர இயக்க லாபம்",
    "GST 18% Tax Collected": "வசூலிக்கப்பட்ட GST 18%",
    "Operational Expense Voucher Logs": "இயக்க செலவு வவுச்சர் பதிவுகள்",
    "Finance, Expenses & GST Tax Ledger": "நிதி, செலவுகள் & GST லெட்ஜர்",
    "Log Operational Expense": "செலவுகளை பதிவு செய்க",
    "Ask SmartMart Pro AI...": "SmartMart Pro AI இடம் கேளுங்கள்...",
    "Analyzing User Console Stream": "பயனர் கன்சோல் பகுப்பாய்வு",
    "QUICK AI PROMPTS": "விரைவான AI கேள்விகள்",
    "Welcome, Supplier Partner": "வரவேற்கிறோம், விநியோகஸ்தர் பங்குதாரர்",
    
    // Reports view glossary additions
    "Financial Ledger & Profit Reports": "நிதி லெட்ஜர் & லாப அறிக்கைகள்",
    "Recent Ledger Transactions": "சமீபத்திய லெட்ஜர் பரிவர்த்தனைகள்",
    "View Full Ledger": "முழு லெட்ஜரையும் காண்க",
    "Expense Breakdown": "செலவு முறிவு",
    "Total Expenses": "மொத்த செலவுகள்",
    "Inventory Purchases": "சரக்கு கொள்முதல்",
    "Staff Salaries": "ஊழியர் சம்பளம்",
    "Store Utilities": "கடை பயன்பாடுகள்",
    "Logistics & Freight": "தளவாடங்கள் & சரக்கு கட்டணம்",
    "Debit": "பற்று",
    "Credit": "வரவு",
    "EXPORT PDF": "PDF ஆக ஏற்றுமதி செய்",
    "EXPORT EXCEL": "EXCEL ஆக ஏற்றுமதி செய்",

    // AI demand forecasting glossary additions
    "Demand Forecasting & Automated Reorders": "தேவை கணிப்பு & தானியங்கி மறுஆர்டர்கள்",
    "Smart Reorder Recommendations": "ஸ்மார்ட் மறுஆர்டர் பரிந்துரைகள்",
    "LAUNCH AI COPILOT CHAT": "AI உதவி அரட்டையைத் தொடங்கு",
    "Customer Cross-Sell Matrix": "வாடிக்கையாளர் குறுக்கு விற்பனை அணி",

    // POS view glossary additions
    "SmartMart Pro Point of Sale (POS) Billing Terminal": "ஸ்மார்ட்மார்ட் புரோ பில்லிங் முனையம் (POS)",
    "OPEN LASER SCANNER": "லேசர் ஸ்கேனரைத் திறக்கவும்",
    "SCAN BARCODE": "பார்கோடு ஸகேன் செய்",
    "SmartMart Pro Basket Items": "கூடை பொருட்கள்",
    "Walk-in Customer": "நேரடி வாடிக்கையாளர்",
    "PRINT SMARTMARTPRO INVOICE & PAY": "இன்வாய்ஸ் அச்சிட்டு பணமளிக்கவும்",
    "GRAND TOTAL": "மொத்த தொகை",
    "Unique SKUs": "தனித்துவ தயாரிப்புகள்",
    "Basket is currently empty": "கூடை தற்போது காலியாக உள்ளது",
    "Scan a barcode or select items from supermarket catalog": "பார்கோடு ஸ்கேன் செய்யவும் அல்லது தயாரிப்புகளைத் தேர்ந்தெடுக்கவும்",
    "Subtotal": "கூட்டுத்தொகை",
    "GST (18%)": "GST (18%)",
    "Cash Payment": "பணப் பணம்",
    "Card / Swipe": "அட்டை செலுத்துதல்",
    "UPI / QR Code": "UPI / QR குறியீடு",
    "SmartMart Wallet": "ஸ்மார்ட்மார்ட் வாலட்",

    // Top Header bar additions
    "Logged in": "உள்நுழைந்துள்ளார்",
    "Branch": "கிளை",
    "ONLINE STOREFRONT": "ஆன்லைன் கடை",
    "ERP ADMIN MODE": "நிர்வாகி பயன்முறை",

    // Inventory view glossary additions
    "Inventory & Stock Control": "சரக்கு & இருப்பு கட்டுப்பாடு",
    "Track SKU stock levels, monitor threshold alerts, and reorder products across branches.": "பொருட்களின் இருப்பு நிலைகளைக் கண்காணித்து மறுஆர்டர் செய்யுங்கள்.",
    "Total Tracked Products": "மொத்த பொருட்கள்",
    "All Categories Active": "அனைத்து பிரிவுகளும் செயலில்",
    "Out of Stock Items": "இருப்பு இல்லாத பொருட்கள்",
    "PO Recommended": "கொள்முதல் ஆர்டர் பரிந்துரைக்கப்படுகிறது",
    "Search catalog by SKU or title...": "சரக்கு பட்டியலைத் தேடுங்கள்...",
    "PRODUCT NAME": "தயாரிப்பு பெயர்",
    "SKU": "SKU குறியீடு",
    "CATEGORY": "பிரிவு",
    "STOCK QTY": "இருப்பு அளவு",
    "REORDER LEVEL": "மறுஆர்டர் அளவு",
    "CRITICAL LEVEL": "முக்கிய இருப்பு அளவு",
    "STATUS": "நிலைமை",
    "ACTION": "நடவடிக்கை",
    "Out of Stock": "இருப்பில் இல்லை",
    "CRITICAL STOCK": "மிகக்குறைந்த இருப்பு",
    "Low Stock": "குறைந்த இருப்பு",
    "In Stock": "இருப்பில் உள்ளது",
    "REORDER PR": "மறுஆர்டர் செய்",
    "Submit Procurement Request": "கொள்முதல் கோரிக்கையை சமர்ப்பிக்கவும்",
    "REORDER QUANTITY": "மறுஆர்டர் அளவு",
    "RECOMMENDED SUPPLIER": "பரிந்துரைக்கப்பட்ட விநியோகஸ்தர்",
    "Cancel": "ரத்துசெய்",
    "Submit Request": "கோரிக்கையை சமர்ப்பி",
    "All": "அனைத்தும்",

    // Products Glossary Additions
    "Organic Fresh Bananas": "இயற்கை புதிய வாழைப்பழம்",
    "A2 Fresh Whole Milk 1L": "A2 புதிய முழு பால் 1லி",
    "Fresh Strawberries 250g": "புதிய ஸ்ட்ராபெர்ரி 250 கிராம்",
    "Greek Yogurt Blueberry 150g": "கிரேக்க தயிர் புளுபெர்ரி 150 கிராம்",
    "Pure Cow Ghee / Butter 500g": "தூய பசு நெய் / வெண்ணெய் 500 கிராம்",
    "Fresh Sourdough Bread Loaf": "புதிய புளிப்பு ரொட்டி",
    "Organic Orange Juice 1L": "இயற்கை ஆரஞ்சு சாறு 1லி",
    "Royal Basmati Rice 5kg": "ராயல் பாசுமதி அரிசி 5 கிலோ",
    "Kashmir Red Apples 1kg": "காஷ்மீர் சிவப்பு ஆப்பிள் 1 கிலோ",
    "Organic Farm Tomatoes 1kg": "இயற்கை பண்ணை தக்காளி 1 கிலோ",
    "Country Farm Eggs (12 Pack)": "நாட்டு பண்ணை முட்டை (12 பேக்)",
    "Amul Paneer / Cheese 200g": "அமுல் பன்னீர் / பாலாடைக்கட்டி 200 கிராம்",
    "Butter Croissant (4 Pack)": "வெண்ணெய் குரோசண்ட் (4 பேக்)",
    "Whole Wheat Atta Bread": "முழு கோதுமை ரொட்டி",
    "Himalayan Natural Mineral Water 1L": "இமயமலை இயற்கை மினரல் வாட்டர் 1லி",
    "Filter Coffee Powder 250g": "பில்டர் காபி தூள் 250 கிராம்",
    "Frozen Green Peas 500g": "உறைந்த பச்சை பட்டாணி 500 கிராம்",
    "Frozen Paneer Tikka Slices": "உறைந்த பன்னீர் டிக்கா துண்டுகள்",
    "Roasted Masala Cashews 200g": "வறுத்த மசாலா முந்திரி 200 கிராம்",
    "Cold Pressed Gingelly Oil 1L": "மரச்செக்கு நல்லெண்ணெய் 1லி",
    "Fresh Green Capsicum 500g": "புதிய பச்சை குடைமிளகாய் 500 கிராம்",
    "Fresh Curd / Dahi 500g": "புதிய தயிர் 500 கிராம்",
    "Munnar CTC Black Tea 250g": "மூணார் சிடிசி கருப்பு தேயிலை 250 கிராம்",
    "Special South Indian Murukku 200g": "சிறப்பு தென்னிந்திய முறுக்கு 200 கிராம்",

    // Login View Glossary Additions
    "Sign In": "உள்நுழைய",
    "Register Customer": "வாடிக்கையாளர் பதிவு",
    "Security Credentials Login": "பாதுகாப்பு சான்றுகள் உள்நுழைவு",
    "Enter your registered email and passphrase to login.": "உள்நுழைய உங்கள் மின்னஞ்சல் மற்றும் கடவுச்சொல்லை உள்ளிடவும்.",
    "Enter your registered email and password to login.": "உள்நுழைய உங்கள் மின்னஞ்சல் மற்றும் கடவுச்சொல்லை உள்ளிடவும்.",
    "EMAIL ADDRESS": "மின்னஞ்சல் முகவரி",
    "PASSPHRASE": "கடவுச்சொல்",
    "PASSWORD": "கடவுச்சொல்",
    "Forgot Passphrase?": "கடவுச்சொல்லை மறந்தீர்களா?",
    "Forgot Password?": "கடவுச்சொல்லை மறந்தீர்களா?",
    "CONFIRM PASSWORD": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    "Remember this device": "இந்த சாதனத்தை நினைவில் கொள்க",
    "LOG IN & DECODE SECURE JWT": "உள்நுழை & JWT ஐ டிகோட் செய்",
    "Create SmartMart Customer Account": "வாடிக்கையாளர் கணக்கை உருவாக்கவும்",
    "Register using your email. We will send a 4-digit security code (OTP) to verify ownership.": "மின்னஞ்சல் மூலம் பதிவு செய்யுங்கள். 4-இலக்க OTP குறியீட்டை அனுப்புவோம்.",
    "SEND VERIFICATION CODE": "சரிபார்ப்புக் குறியீட்டை அனுப்பவும்",
    "Enter Verification Code": "சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்",
    "Verify OTP": "OTP ஐ சரிபார்க்கவும்",
    "RETAIL ERP SYSTEM": "சில்லறை வணிக ERP",
    "SmartMart Pro Enterprise Platform": "ஸ்மார்ட்மார்ட் புரோ நிறுவனம்",
    "A full digital ecosystem unifying multi-branch grocery ERP backoffice with online store front, delivery OTP verification, and AI demand forecasting.": "முழுமையான டிஜிட்டல் சுற்றுச்சூழல் சில்லறை வணிக ERP தளம்.",
    "Multi-role dashboard with RBAC routing": "பங்கு அடிப்படையிலான கட்டுப்பாட்டு பலகை",
    "E-Commerce storefront with wallet payment": "வாலட் கட்டணத்துடன் மின் வணிக கடை",
    "Fleet delivery dispatch & OTP Verification": "OTP சரிபார்ப்புடன் டெலிவரி கடற்படை",
    "Accountant Ledger & GST reports": "கணக்காளர் லெட்ஜர் & GST அறிக்கைகள்",
    "256-Bit Encrypted Terminal": "256-பிட் குறியாக்கப்பட்ட முனையம்"
  },
  hi: {
    "Pending Procurement Reorder Requests": "लंबित खरीद अनुरोध",
    "Awaiting Manager PO Issuance": "प्रबंधक की मंजूरी की प्रतीक्षा",
    "No pending purchase requests. All branch inventory healthy.": "कोई लंबित खरीद अनुरोध नहीं है।",
    "Approve & Issue PO": "स्वीकृत करें और PO जारी करें",
    "Issued Purchase Orders (POs)": "जारी किए गए खरीद आदेश (PO)",
    "POs sent from SmartMart Pro procurement manager.": "खरीद प्रबंधक से भेजे गए आदेश।",
    "No active purchase orders found.": "कोई सक्रिय खरीद आदेश नहीं मिला।",
    "AWAITING WAREHOUSE VERIFICATION": "गोदाम सत्यापन की प्रतीक्षा है",
    "ACCEPT PO": "ऑर्डर स्वीकार करें",
    "MARK SHIPPED": "भेजा गया चिह्नित करें",
    "MARK DELIVERED": "वितरित चिह्नित करें",
    "Incoming Shipments Verification": "आने वाले शिपमेंट का सत्यापन",
    "Count and verify delivered supplier shipments before updating store inventory.": "स्टॉक अपडेट करने से पहले डिलीवरी सत्यापन करें।",
    "No delivered supplier orders waiting in the warehouse queue.": "कोई ऑर्डर प्रतीक्षा में नहीं है।",
    "RECEIVED QTY": "प्राप्त मात्रा",
    "DAMAGED QTY": "क्षतिग्रस्त मात्रा",
    "VERIFY & UPDATE INVENTORY": "सत्यापित करें और स्टॉक अपडेट करें",
    "Secure Handover OTP": "सुरक्षित हैंडओवर OTP",
    "Confirm & Mark Delivered": "पुष्टि करें और वितरित चिह्नित करें",
    "Online Customer Storefront": "ऑनलाइन ग्राहक स्टोरफ्रंट",
    "Fresh organic produce, dairy, bakery, beverages & pantry items delivered straight to your home in 10 minutes.": "10 मिनट में सीधे आपके घर पर जैविक उत्पाद।",
    "Shop Catalog": "कैटलॉग देखें",
    "My Basket": "मेरी टोकरी",
    "Live Delivery Tracking & Reviews": "लाइव डिलीवरी ट्रैकिंग और समीक्षा",
    "Shopping Basket": "शॉपिंग बास्केट",
    "Review selected items before triggering online payment gateway.": "भुगतान करने से पहले वस्तुओं की समीक्षा करें।",
    "Checkout Gateway": "चेकआउट गेटवे",
    "FILE 18% GST RETURN": "18% जीएसटी रिटर्न दाखिल करें",
    "LOG NEW EXPENSE": "नया खर्च दर्ज करें",
    "Gross Revenue (YTD)": "कुल राजस्व",
    "Operating Expenses": "परिचालन व्यय",
    "Net Operating Profit": "शुद्ध परिचालन लाभ",
    "GST 18% Tax Collected": "जीएसटी 18% कर एकत्रित",
    "Operational Expense Voucher Logs": "व्यय वाउचर लॉग",
    "Finance, Expenses & GST Tax Ledger": "वित्त, व्यय और जीएसटी टैक्स लेजर",
    "Log Operational Expense": "परिचालन व्यय दर्ज करें",
    "Ask SmartMart Pro AI...": "स्मार्टमार्ट प्रो एआई से पूछें...",
    "Analyzing User Console Stream": "उपयोगकर्ता कंसोल विश्लेषण",
    "QUICK AI PROMPTS": "त्वरित एआई संकेत",
    "Welcome, Supplier Partner": "स्वागत है, आपूर्तिकर्ता भागीदार",

    // Reports view glossary additions
    "Financial Ledger & Profit Reports": "वित्तीय लेजर और लाभ रिपोर्ट",
    "Recent Ledger Transactions": "हाल के लेजर लेनदेन",
    "View Full Ledger": "पूरा लेजर देखें",
    "Expense Breakdown": "व्यय विश्लेषण",
    "Total Expenses": "कुल खर्च",
    "Inventory Purchases": "इन्वेंटरी खरीद",
    "Staff Salaries": "कर्मचारी वेतन",
    "Store Utilities": "दुकान उपयोगिताएँ",
    "Logistics & Freight": "लॉजिस्टिक्स और माल ढुलाई",
    "Debit": "डेबिट (नाम)",
    "Credit": "क्रेडिट (जमा)",
    "EXPORT PDF": "पीडीएफ निर्यात करें",
    "EXPORT EXCEL": "एक्सेल निर्यात करें",

    // AI demand forecasting glossary additions
    "Demand Forecasting & Automated Reorders": "मांग पूर्वानुमान और स्वचालित रीऑर्डर",
    "Smart Reorder Recommendations": "स्मार्ट रीऑर्डर सिफारिशें",
    "LAUNCH AI COPILOT CHAT": "एआई को-पायलट चैट लॉन्च करें",
    "Customer Cross-Sell Matrix": "ग्राहक क्रॉस-सेल मैट्रिक्स",

    // POS view glossary additions
    "SmartMart Pro Point of Sale (POS) Billing Terminal": "स्मार्टमार्ट प्रो पॉइंट ऑफ सेल (POS) बिलिंग टर्मिनल",
    "OPEN LASER SCANNER": "लेजर स्कैनर खोलें",
    "SCAN BARCODE": "बारकोड स्कैन करें",
    "SmartMart Pro Basket Items": "टोकरी के सामान",
    "Walk-in Customer": "प्रत्यक्ष ग्राहक",
    "PRINT SMARTMARTPRO INVOICE & PAY": "इनवॉइस प्रिंट करें और भुगतान करें",
    "GRAND TOTAL": "कुल योग",
    "Unique SKUs": "विशिष्ट उत्पाद",
    "Basket is currently empty": "टोकरी वर्तमान में खाली है",
    "Scan a barcode or select items from supermarket catalog": "बारकोड स्कैन करें या कैटलॉग से चुनें",
    "Subtotal": "उप-योग",
    "GST (18%)": "जीएसटी (18%)",
    "Cash Payment": "नकद भुगतान",
    "Card / Swipe": "कार्ड भुगतान",
    "UPI / QR Code": "यूपीआई भुगतान",
    "SmartMart Wallet": "स्मार्टमार्ट वॉलेट",

    // Top Header bar additions
    "Logged in": "लॉग इन किया",
    "Branch": "शाखा",
    "ONLINE STOREFRONT": "ऑनलाइन स्टोर",
    "ERP ADMIN MODE": "व्यवस्थापक मोड",

    // Inventory view glossary additions
    "Inventory & Stock Control": "इन्वेंटरी और स्टॉक नियंत्रण",
    "Track SKU stock levels, monitor threshold alerts, and reorder products across branches.": "स्टॉक स्तरों को ट्रैक करें और शाखाओं में उत्पादों को फिर से व्यवस्थित करें।",
    "Total Tracked Products": "कुल ट्रैक किए गए उत्पाद",
    "All Categories Active": "सभी श्रेणियां सक्रिय",
    "Out of Stock Items": "स्टॉक से बाहर आइटम",
    "PO Recommended": "क्रय आदेश की अनुशंसा",
    "Search catalog by SKU or title...": "कैटलॉग खोजें...",
    "PRODUCT NAME": "उत्पाद का नाम",
    "SKU": "SKU",
    "CATEGORY": "श्रेणी",
    "STOCK QTY": "स्टॉक मात्रा",
    "REORDER LEVEL": "रीऑर्डर स्तर",
    "CRITICAL LEVEL": "महत्वपूर्ण स्तर",
    "STATUS": "स्थिति",
    "ACTION": "कार्रवाई",
    "Out of Stock": "स्टॉक में नहीं है",
    "CRITICAL STOCK": "गंभीर स्टॉक",
    "Low Stock": "कम स्टॉक",
    "In Stock": "स्टॉक में",
    "REORDER PR": "पुनः ऑर्डर करें",
    "Submit Procurement Request": "खरीद अनुरोध सबमिट करें",
    "REORDER QUANTITY": "रीऑर्डर मात्रा",
    "RECOMMENDED SUPPLIER": "अनुशंसित आपूर्तिकर्ता",
    "Cancel": "रद्द करें",
    "Submit Request": "अनुरोध सबमिट करें",
    "All": "सभी",

    // Products Glossary Additions
    "Organic Fresh Bananas": "जैविक ताजा केला",
    "A2 Fresh Whole Milk 1L": "A2 ताजा दूध 1 लीटर",
    "Fresh Strawberries 250g": "ताजा स्ट्रॉबेरी 250 ग्राम",
    "Greek Yogurt Blueberry 150g": "ग्रीक योगर्ट ब्लूबेरी 150 ग्राम",
    "Pure Cow Ghee / Butter 500g": "शुद्ध गाय का घी / मक्खन 500 ग्राम",
    "Fresh Sourdough Bread Loaf": "ताजा खट्टा ब्रेड",
    "Organic Orange Juice 1L": "जैविक संतरे का रस 1 लीटर",
    "Royal Basmati Rice 5kg": "रॉयल बासमती चावल 5 किलो",
    "Kashmir Red Apples 1kg": "कश्मीर लाल सेब 1 किलो",
    "Organic Farm Tomatoes 1kg": "जैविक फार्म टमाटर 1 किलो",
    "Country Farm Eggs (12 Pack)": "देसी अंडे (12 का पैक)",
    "Amul Paneer / Cheese 200g": "अमुल पनीर / चीज 200 ग्राम",
    "Butter Croissant (4 Pack)": "मक्खन क्रोइसैन (4 पैक)",
    "Whole Wheat Atta Bread": "गेहूं की ब्रेड",
    "Himalayan Natural Mineral Water 1L": "हिमालयन मिनरल वाटर 1 लीटर",
    "Filter Coffee Powder 250g": "फिल्टर कॉफी पाउडर 250 ग्राम",
    "Frozen Green Peas 500g": "फ्रोजन हरी मटर 500 ग्राम",
    "Frozen Paneer Tikka Slices": "फ्रोजन पनीर टिक्का स्लाइस",
    "Roasted Masala Cashews 200g": "भुना हुआ मसाला काजू 200 ग्राम",
    "Cold Pressed Gingelly Oil 1L": "कोल्ड प्रेस्ड तिल का तेल 1 लीटर",
    "Fresh Green Capsicum 500g": "ताजा हरी शिमला मिर्च 500 ग्राम",
    "Fresh Curd / Dahi 500g": "ताजा दही 500 ग्राम",
    "Munnar CTC Black Tea 250g": "मुन्नार सीटीसी काली चाय 250 ग्राम",
    "Special South Indian Murukku 200g": "विशेष दक्षिण भारतीय मुरुक्कू 200 ग्राम",

    // Login View Glossary Additions
    "Sign In": "साइन इन करें",
    "Register Customer": "ग्राहक पंजीकरण",
    "Security Credentials Login": "सुरक्षा क्रेडेंशियल लॉगिन",
    "Enter your registered email and passphrase to login.": "लॉग इन करने के लिए अपना पंजीकृत ईमेल और पासवर्ड दर्ज करें।",
    "Enter your registered email and password to login.": "लॉग इन करने के लिए अपना पंजीकृत ईमेल और पासवर्ड दर्ज करें।",
    "EMAIL ADDRESS": "ईमेल पता",
    "PASSPHRASE": "पासवर्ड",
    "PASSWORD": "पासवर्ड",
    "Forgot Passphrase?": "पासवर्ड भूल गए?",
    "Forgot Password?": "पासवर्ड भूल गए?",
    "CONFIRM PASSWORD": "पासवर्ड की पुष्टि करें",
    "Remember this device": "इस डिवाइस को याद रखें",
    "LOG IN & DECODE SECURE JWT": "लॉग इन करें और JWT डिकोड करें",
    "Create SmartMart Customer Account": "ग्राहक खाता बनाएं",
    "Register using your email. We will send a 4-digit security code (OTP) to verify ownership.": "ईमेल से पंजीकरण करें। हम सत्यापित करने के लिए 4 अंकों का कोड (OTP) भेजेंगे।",
    "SEND VERIFICATION CODE": "सत्यापन कोड भेजें",
    "Enter Verification Code": "सत्यापन कोड दर्ज करें",
    "Verify OTP": "ओटीपी सत्यापित करें",
    "RETAIL ERP SYSTEM": "रिटेल ईआरपी सिस्टम",
    "SmartMart Pro Enterprise Platform": "स्मार्टमार्ट प्रो एंटरप्राइज प्लेटफॉर्म",
    "A full digital ecosystem unifying multi-branch grocery ERP backoffice with online store front, delivery OTP verification, and AI demand forecasting.": "मल्टी-ब्रांच ग्रोसरी ईआरपी बैकऑफ़िस को ऑनलाइन स्टोरफ्रंट के साथ एकीकृत करने वाला डिजिटल इकोसिस्टम।",
    "Multi-role dashboard with RBAC routing": "आरबीएसी रूटिंग के साथ बहु-भूमिका डैशबोर्ड",
    "E-Commerce storefront with wallet payment": "वॉलेट भुगतान के साथ ई-कॉमर्स स्टोरफ्रंट",
    "Fleet delivery dispatch & OTP Verification": "बेड़ा वितरण प्रेषण और ओटीपी सत्यापन",
    "Accountant Ledger & GST reports": "अकाउंटेंट लेजर और जीएसटी रिपोर्ट",
    "256-Bit Encrypted Terminal": "256-बिट एन्क्रिप्टेड टर्मिनल"
  },
  ml: {
    "Pending Procurement Reorder Requests": "തീർപ്പാക്കാത്ത ഓർഡർ അഭ്യർത്ഥനകൾ",
    "Awaiting Manager PO Issuance": "മാനേജർ അനുമതിക്കായി കാത്തിരിക്കുന്നു",
    "No pending purchase requests. All branch inventory healthy.": "അഭ്യർത്ഥനകൾ ഒന്നും തന്നെ നിലവിലില്ല.",
    "Approve & Issue PO": "അംഗീകരിച്ചു PO അയക്കുക",
    "Issued Purchase Orders (POs)": "അയച്ച ഓർഡറുകൾ (POs)",
    "POs sent from SmartMart Pro procurement manager.": "മാനേജർ അയച്ച ഓർഡറുകൾ.",
    "No active purchase orders found.": "ഓർഡറുകൾ ഒന്നും കണ്ടെത്തിയില്ല.",
    "AWAITING WAREHOUSE VERIFICATION": "വെയർഹൗസ് പരിശോധനക്കായി കാത്തിരിക്കുന്നു",
    "ACCEPT PO": "ഓർഡർ സ്വീകരിക്കുക",
    "MARK SHIPPED": "അയച്ചതായി രേഖപ്പെടുത്തുക",
    "MARK DELIVERED": "ഡെലിവറി ചെയ്തതായി രേഖപ്പെടുത്തുക",
    "Incoming Shipments Verification": "വരുന്ന വിതരണങ്ങളുടെ പരിശോധന",
    "Count and verify delivered supplier shipments before updating store inventory.": "സ്റ്റോക്ക് അപ്ഡേറ്റ് ചെയ്യുന്നതിന് മുൻപ് പരിശോധിക്കുക.",
    "No delivered supplier orders waiting in the warehouse queue.": "കാത്തിരിക്കുന്ന ഓർഡറുകൾ ഒന്നും തന്നെയില്ല.",
    "RECEIVED QTY": "ലഭിച്ച അളവ്",
    "DAMAGED QTY": "കേടുപാടുകൾ വന്ന അളവ്",
    "VERIFY & UPDATE INVENTORY": "പരിശോധിച്ചു സ്റ്റോക്ക് പുതുക്കുക",
    "Secure Handover OTP": "സുരക്ഷിത ഹാൻഡ്ഓവർ OTP",
    "Confirm & Mark Delivered": "ഡെലിവറി ഉറപ്പുവരുത്തുക",
    "Online Customer Storefront": "ഓൺ‌ലൈൻ കസ്റ്റമർ സ്റ്റോർഫ്രണ്ട്",
    "Fresh organic produce, dairy, bakery, beverages & pantry items delivered straight to your home in 10 minutes.": "10 മിനിറ്റിനുള്ളിൽ വീട്ടിലെത്തിക്കുന്ന ഉൽപ്പന്നങ്ങൾ.",
    "Shop Catalog": "ഉൽപ്പന്നങ്ങൾ കാണുക",
    "My Basket": "എന്റെ ബാസ്കറ്റ്",
    "Live Delivery Tracking & Reviews": "ലൈവ് ട്രാക്കിംഗും അവലോകനങ്ങളും",
    "Shopping Basket": "ഷോപ്പിംഗ് ബാസ്കറ്റ്",
    "Review selected items before triggering online payment gateway.": "പണമടയ്ക്കുന്നതിന് മുൻപ് ഉൽപ്പന്നങ്ങൾ പരിശോധിക്കുക.",
    "Checkout Gateway": "ചെക്ക്ഔട്ട് ഗേറ്റ്‌വേ",
    "FILE 18% GST RETURN": "18% ജിഎസ്ടി റിട്ടേൺ ഫയൽ ചെയ്യുക",
    "LOG NEW EXPENSE": "പുതിയ ചിലവുകൾ രേഖപ്പെടുത്തുക",
    "Gross Revenue (YTD)": "ആകെ വരുമാനം",
    "Operating Expenses": "പ്രവർത്തന ചിലവുകൾ",
    "Net Operating Profit": "ലാഭം",
    "GST 18% Tax Collected": "ശേഖരിച്ച ജിഎസ്ടി 18%",
    "Operational Expense Voucher Logs": "ചിലവ് രേഖകൾ",
    "Finance, Expenses & GST Tax Ledger": "ധനകാര്യം, ചിലവുകൾ & ജിഎസ്ടി ലെഡ്ജർ",
    "Log Operational Expense": "ചിലവുകൾ രേഖപ്പെടുത്തുക",
    "Ask SmartMart Pro AI...": "SmartMart Pro AI യോട് ചോദിക്കൂ...",
    "Analyzing User Console Stream": "യൂസർ കൺസോൾ പരിശോധന",
    "QUICK AI PROMPTS": "AI ചോദ്യങ്ങൾ",
    "Welcome, Supplier Partner": "സ്വാഗതം, വിതരണക്കാരൻ",

    // Reports view glossary additions
    "Financial Ledger & Profit Reports": "ധനകാര്യ ലെഡ്ജറും ലാഭ റിപ്പോർട്ടുകളും",
    "Recent Ledger Transactions": "സമീപകാല ഇടപാടുകൾ",
    "View Full Ledger": "പൂർണ്ണ ലെഡ്ജർ കാണുക",
    "Expense Breakdown": "ചിലവ് വിശകലനം",
    "Total Expenses": "ആകെ ചിലവുകൾ",
    "Inventory Purchases": "ഇൻവെന്ററി വാങ്ങലുകൾ",
    "Staff Salaries": "ജീവനക്കാരുടെ ശമ്പളം",
    "Store Utilities": "യൂട്ടിലിറ്റി ചിലവുകൾ",
    "Logistics & Freight": "ലോജിസ്റ്റിക്സ് ചിലവുകൾ",
    "Debit": "ഡെബിറ്റ്",
    "Credit": "ക്രെഡിറ്റ്",
    "EXPORT PDF": "PDF ആക്കുക",
    "EXPORT EXCEL": "EXCEL ആക്കുക",

    // AI demand forecasting glossary additions
    "Demand Forecasting & Automated Reorders": "ഡിമാൻഡ് ഫോർകാസ്റ്റിംഗും ഓട്ടോമേറ്റഡ് റീഓർഡറുകളും",
    "Smart Reorder Recommendations": "സ്മാർട്ട് റീഓർഡർ ശുപാർശകൾ",
    "LAUNCH AI COPILOT CHAT": "എഐ കോ-പൈലറ്റ് ചാറ്റ് ആരംഭിക്കുക",
    "Customer Cross-Sell Matrix": "കസ്റ്റമർ ക്രോസ്സ്-സെൽ മാട്രിക്സ്",

    // POS view glossary additions
    "SmartMart Pro Point of Sale (POS) Billing Terminal": "സ്മാർട്ട്മാർട്ട് പ്രൊ ബില്ലിംഗ് ടെർമിനൽ (POS)",
    "OPEN LASER SCANNER": "ലേസർ സ്കാനർ തുറക്കുക",
    "SCAN BARCODE": "ബാക്കോഡ് സ്കാനുക",
    "SmartMart Pro Basket Items": "ബാസ്കറ്റ് ഐറ്റംസ്",
    "Walk-in Customer": "വാക്ക്-ഇൻ കസ്റ്റമർ",
    "PRINT SMARTMARTPRO INVOICE & PAY": "ഇൻവോയ്സ് പ്രിന്റ് ചെയ്യുക & അടയ്ക്കുക",
    "GRAND TOTAL": "ആകെ തുക",
    "Unique SKUs": "തനിമയുള്ള ഉൽപ്പന്നങ്ങൾ",
    "Basket is currently empty": "ബാസ്കറ്റ് നിലവിൽ കാലിയാണ്",
    "Scan a barcode or select items from supermarket catalog": "ബാക്കോഡ് സ്കാൻ ചെയ്യുക അല്ലെങ്കിൽ ലിസ്റ്റിൽ നിന്ന് തിരഞ്ഞെടുക്കുക",
    "Subtotal": "സബ് ടോട്ടൽ",
    "GST (18%)": "GST (18%)",
    "Cash Payment": "ക്യാഷ് പേയ്മെന്റ്",
    "Card / Swipe": "കാർഡ് പേയ്മെന്റ്",
    "UPI / QR Code": "യുപിഐ പേയ്മെന്റ്",
    "SmartMart Wallet": "സ്മാർട്ട്മാർട്ട് വാലറ്റ്",

    // Top Header bar additions
    "Logged in": "ലോഗിൻ ചെയ്തു",
    "Branch": "ബ്രാഞ്ച്",
    "ONLINE STOREFRONT": "ഓൺലൈൻ സ്റ്റോർ",
    "ERP ADMIN MODE": "അഡ്മിൻ മോഡ്",

    // Inventory view glossary additions
    "Inventory & Stock Control": "ഇൻവെന്ററിയും സ്റ്റോക്ക് നിയന്ത്രണവും",
    "Track SKU stock levels, monitor threshold alerts, and reorder products across branches.": "സ്റ്റോക്ക് നിലകൾ ട്രാക്ക് ചെയ്യുകയും ഉൽപ്പന്നങ്ങൾ റീഓർഡർ ചെയ്യുകയും ചെയ്യുക.",
    "Total Tracked Products": "ആകെ ഉൽപ്പന്നങ്ങൾ",
    "All Categories Active": "എല്ലാ വിഭാഗങ്ങളും സജീവം",
    "Out of Stock Items": "സ്റ്റോക്കില്ലാത്ത ഉൽപ്പന്നങ്ങൾ",
    "PO Recommended": "ഓർഡർ ശുപാർശ ചെയ്യുന്നു",
    "Search catalog by SKU or title...": "വിവരങ്ങൾ തിരയുക...",
    "PRODUCT NAME": "ഉൽപ്പന്നത്തിന്റെ പേര്",
    "SKU": "SKU",
    "CATEGORY": "വിഭാഗം",
    "STOCK QTY": "സ്റ്റോക്ക് അളവ്",
    "REORDER LEVEL": "റീഓർഡർ ലെവൽ",
    "CRITICAL LEVEL": "നിർണായക അളവ്",
    "STATUS": "നില",
    "ACTION": "നടപടി",
    "Out of Stock": "സ്റ്റോക്കില്ല",
    "CRITICAL STOCK": "നിർണായക സ്റ്റോക്ക്",
    "Low Stock": "കുറഞ്ഞ സ്റ്റോക്ക്",
    "In Stock": "സ്റ്റോക്കുണ്ട്",
    "REORDER PR": "റീഓർഡർ ചെയ്യുക",
    "Submit Procurement Request": "ഓർഡർ അഭ്യർത്ഥന സമർപ്പിക്കുക",
    "REORDER QUANTITY": "റീഓർഡർ അളവ്",
    "RECOMMENDED SUPPLIER": "വിതരണക്കാരൻ",
    "Cancel": "റദ്ദാക്കുക",
    "Submit Request": "അഭ്യർത്ഥിക്കുക",
    "All": "എല്ലാം",

    // Products Glossary Additions
    "Organic Fresh Bananas": "ഓർഗാനിക് പഴം",
    "A2 Fresh Whole Milk 1L": "A2 നല്ല പാല് 1 ലിറ്റർ",
    "Fresh Strawberries 250g": "സ്ട്രോബെറി 250 ഗ്രാം",
    "Greek Yogurt Blueberry 150g": "ഗ്രീക്ക് തൈര് ബ്ലൂബെറി 150 ഗ്രാം",
    "Pure Cow Ghee / Butter 500g": "ശുദ്ധമായ പശുവിൻ നെയ്യ് / വെണ്ണ 500 ഗ്രാം",
    "Fresh Sourdough Bread Loaf": "നല്ല ബ്രെഡ്",
    "Organic Orange Juice 1L": "ഓർഗാനിക് ഓറഞ്ച് ജ്യൂസ് 1 ലിറ്റർ",
    "Royal Basmati Rice 5kg": "ബാസ്മതി അരി 5 കിലോ",
    "Kashmir Red Apples 1kg": "കാശ്മീർ ചുവന്ന ആപ്പിൾ 1 കിലോ",
    "Organic Farm Tomatoes 1kg": "തക്കാളി 1 കിലോ",
    "Country Farm Eggs (12 Pack)": "നാടൻ കോഴിമുട്ട (12 എണ്ണം)",
    "Amul Paneer / Cheese 200g": "അമുൽ പനീർ / ചീസ് 200 ഗ്രാം",
    "Butter Croissant (4 Pack)": "ക്രോസന്റ് (4 എണ്ണം)",
    "Whole Wheat Atta Bread": "ഗോതമ്പ് ബ്രെഡ്",
    "Himalayan Natural Mineral Water 1L": "മിനറൽ വാട്ടർ 1 ലിറ്റർ",
    "Filter Coffee Powder 250g": "ഫിൽട്ടർ കോഫി പൗഡർ 250 ഗ്രാം",
    "Frozen Green Peas 500g": "ഗ്രീൻ പീസ് 500 ഗ്രാം",
    "Frozen Paneer Tikka Slices": "പനീർ ടിക്ക സ്ലൈസുകൾ",
    "Roasted Masala Cashews 200g": "മസാല കശുവണ്ടി 200 ഗ്രാം",
    "Cold Pressed Gingelly Oil 1L": "നല്ലെണ്ണ 1 ലിറ്റർ",
    "Fresh Green Capsicum 500g": "പച്ച കുടമുളക് 500 ഗ്രാം",
    "Fresh Curd / Dahi 500g": "നല്ല തൈര് 500 ഗ്രാം",
    "Munnar CTC Black Tea 250g": "മൂന്നാർ ബ്ലാക്ക് ടീ 250 ഗ്രാം",
    "Special South Indian Murukku 200g": "കേരളാ മുറുക്ക് 200 ഗ്രാം",

    // Login View Glossary Additions
    "Sign In": "ലോഗിൻ ചെയ്യുക",
    "Register Customer": "രജിസ്ട്രേഷൻ",
    "Security Credentials Login": "ലോഗിൻ ചെയ്യുക",
    "Enter your registered email and passphrase to login.": "ഇമെയിൽ വിലാസവും പാസ്‌വേഡും നൽകുക.",
    "Enter your registered email and password to login.": "ഇമെയിൽ വിലാസവും പാസ്‌വേഡും നൽകുക.",
    "EMAIL ADDRESS": "ഇമെയിൽ വിലാസം",
    "PASSPHRASE": "പാസ്‌വേഡ്",
    "PASSWORD": "പാസ്‌വേഡ്",
    "Forgot Passphrase?": "പാസ്‌വേഡ് മറന്നോ?",
    "Forgot Password?": "പാസ്‌വേഡ് മറന്നോ?",
    "CONFIRM PASSWORD": "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    "Remember this device": "ഓർത്തു വെക്കുക",
    "LOG IN & DECODE SECURE JWT": "ലോഗിൻ ചെയ്യുക",
    "Create SmartMart Customer Account": "കസ്റ്റമർ അക്കൗണ്ട് ഉണ്ടാക്കുക",
    "Register using your email. We will send a 4-digit security code (OTP) to verify ownership.": "ഇമെയിൽ നൽകുക. ഞങ്ങൾ ഒരു OTP കോഡ് അയക്കുന്നതായിരിക്കും.",
    "SEND VERIFICATION CODE": "OTP കോഡ് അയക്കുക",
    "Enter Verification Code": "OTP കോഡ് നൽകുക",
    "Verify OTP": "വെരിഫൈ ചെയ്യുക",
    "RETAIL ERP SYSTEM": "റീട്ടെയിൽ ഇആർപി സിസ്റ്റം",
    "SmartMart Pro Enterprise Platform": "SmartMart Pro പ്ലാറ്റ്ഫോം",
    "A full digital ecosystem unifying multi-branch grocery ERP backoffice with online store front, delivery OTP verification, and AI demand forecasting.": "ഗ്രോസറി ഇആർപി സപ്പോർട്ട് സിസ്റ്റം.",
    "Multi-role dashboard with RBAC routing": "ഡാഷ്‌ബോർഡ് സപ്പോർട്ട് സിസ്റ്റം",
    "E-Commerce storefront with wallet payment": "ഓൺലൈൻ സ്റ്റോർ സംവിധാനം",
    "Fleet delivery dispatch & OTP Verification": "ഡെലിവറി വെരിഫിക്കേഷൻ സിസ്റ്റം",
    "Accountant Ledger & GST reports": "അക്കൗണ്ടിംഗ് റിപ്പോർട്ടുകൾ",
    "256-Bit Encrypted Terminal": "സെക്യൂർ ടെർമിനൽ"
  },
  te: {
    "Sign In": "లాగిన్ అవ్వండి",
    "Register Customer": "ఖాతా నమోదు",
    "Security Credentials Login": "లాగిన్ వివరాలు",
    "EMAIL ADDRESS": "ఈమెయిల్ చిరునామా",
    "PASSWORD": "పాస్‌వర్డ్",
    "Log In": "లాగిన్ చేయండి",
    "Shopping Basket": "షాపింగ్ బాస్కెట్",
    "GRAND TOTAL": "మొత్తం ధర",
    "In Stock": "స్టాక్‌లో ఉంది",
    "Out of Stock": "స్టాక్ లేదు",
    "Low Stock": "తక్కువ స్టాక్",
    "Branch": "శాఖ"
  },
  kn: {
    "Sign In": "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    "Register Customer": "ಖಾತೆ ನೋಂದಣಿ",
    "Security Credentials Login": "ಲಾಗಿನ್ ವಿವರಗಳು",
    "EMAIL ADDRESS": "ಇಮೇಲ್ ವಿಳಾಸ",
    "PASSWORD": "ಪಾಸ್‌ವರ್ಡ್",
    "Log In": "ಲಾಗಿನ್ ಮಾಡಿ",
    "Shopping Basket": "ಶಾಪಿಂಗ್ ബാಸ್ಕೆಟ್",
    "GRAND TOTAL": "ಒಟ್ಟು ಮೊತ್ತ",
    "In Stock": "ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ",
    "Out of Stock": "ಸ್ಟಾಕ್ ಇಲ್ಲ",
    "Low Stock": "ಕಡಿಮೆ ಸ್ಟಾಕ್",
    "Branch": "ಶಾಖೆ"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('smartmart_lang') || 'en';
  });

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('smartmart_lang', newLang);
  };

  const t = (key) => {
    if (!key) return '';
    const trimmed = key.trim();
    if (TRANSLATIONS[lang] && TRANSLATIONS[lang][trimmed]) {
      return TRANSLATIONS[lang][trimmed];
    }
    if (TRANSLATIONS.en[trimmed] && TRANSLATIONS[lang][trimmed]) {
      return TRANSLATIONS[lang][trimmed];
    }
    if (GLOSSARY[lang] && GLOSSARY[lang][trimmed]) {
      return GLOSSARY[lang][trimmed];
    }
    // Case-insensitive match in Glossary
    if (GLOSSARY[lang]) {
      const lowerKey = trimmed.toLowerCase();
      const matchKey = Object.keys(GLOSSARY[lang]).find(k => k.toLowerCase() === lowerKey);
      if (matchKey) {
        return GLOSSARY[lang][matchKey];
      }
    }
    // Case-insensitive match in TRANSLATIONS
    if (TRANSLATIONS[lang]) {
      const lowerKey = trimmed.toLowerCase();
      const matchKey = Object.keys(TRANSLATIONS[lang]).find(k => k.toLowerCase() === lowerKey);
      if (matchKey) {
        return TRANSLATIONS[lang][matchKey];
      }
    }
    return TRANSLATIONS.en[trimmed] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
